# Generated by Django 5.2 on 2025-04-28 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_username_student_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='uname',
            new_name='username',
        ),
    ]
